const express = require('express')
const fs = require('fs')
const index = require('./public/assets/js/index')

const app = express()

//set the port 
const PORT = process.env.PORT || 3000


app.use( express.static('html') )
// accept incoming POST requests
app.use(express.urlencoded({ extended: true }))
app.use(express.json())

//Data - get previous notes
app.get("/api/notes", async function(req, res) {
    // making a request for data
    const notes = await fs.readFile('./db/db.json', 'utf8');
    console.log( `getting previous notes.. ${notes} `)
    res.render("notes", { allNotes: notes });
});
//save the note items generated by notes.html======



// let noteListItems = fs.existsSync(saveFile) ?
//     JSON.parse( fs.readFileSync(saveFile) ) : []

//Routes ==


app.post('/api/notes', function(req, res) {
    console.log( '[POST /api/notes]', req.body )
    const newNote = req.body
    console.log( `[notes] noteList(${noteListItems.length} entries), adding: \n`, newNote)
    noteListItems.push( newNote )
    // save to a file, as a string like localStorage
    fs.writeFileSync( saveFile, JSON.stringify( noteListItems ) )

    res.send( { message: `New Note Added *${newNote.title}*` } )
});
app.listen(PORT, function() {
    console.log( `Server listening on: http://localhost:${PORT}` );
  })
